export const localLanguage = {
    VIEW:'view',
    UPDATE:'update',
    DELETE:'delete',
    DEPT_NAME:'Dept Name ',
    HOD:'HOD',
    LOCATION:'location',
    UPDATE_DEPARTMENT:'Update Department',
    TOTAL_EMPLOYEES:'Total employees ',
    EMPLOYEES:'Employees',
    HOD_S:'hod',
    MSG_DEPT:'Enter department head name',
    HOD_PLACEHOLDER:'Head of department',
    MSG_LOCATION_OF_HEAD:'Enter location of head',
    LOCATION_OF_HEAD:'Location of head',
    DEPT_NAME:'Dept name: ',
    DEPTNAME:'deptName',
    NAME:"Name",
    NO_OF_EMPLOYEES:'No. of Empployees : ',
    NUMEMPLOYEES:'numEmployees',
    EMAIL:'Email',
    VIEW_DEPT:'View Dept',
    VIEW_EMP:'View Emp',
    LOGOUT:'LogOut',
    ADD_DEPARTMENT:'Add Department',
    ENTER_NAME:'Enter Name : ',
    DEPARTMENT_ALREADY_EXIST:'Department already exist',
    ADD:'Add',
    ASSIGN_DEPT:'Assign-dept',
    NOT_HIRED:"Not Hired",
    SELECT_DEPT:'Select Department',
    ASSIGN:'Assign',
    EMPLOYEE_DETAILS:'Employee Details',
    DEPARTMENT:'Department',
    SUCCESS:"success", 
    LOGGED_IN:"Logged in",
    EMPLOYEE:"employee",
    MANAGER:'manager',
    ERROR:"error", 
    LOGIN_FAILED:"Login Failed",
    USER:"user",
    USER_MSG:"Please select User type!",
    SELECT_USER_TYPE:"select user type",
    EMAIL_S:"email",
    ENTER_EMAIL:"Enter email",
    PASSWORD:"password",
    ENTER_PASSWORD:"Enter password",
    INVALID:'Invalid',
    LOGIN:'Login',
    SIGNUP:"Signup",
    ORGANISATION_PORTAL:'ORGANISATION PORTAL',
    LOGIN_S:"login",
    SIGNUP_S:"signup",
    SIGN_UP:'Sign-up',
    LOG_IN:'Log-in',
    SLICE:"slice",
    CREATE_DEPT:'Create Dept',  
}

export const routerConstants ={
    HOME_ROUTE:"/",
    VIEW_DEPARTMENT_ROUTE:"/dept-mgmt/dept-list",
    VIEW_EMPLOYEE_ROUTE:"/dept-mgmt/emp-list",
    DEPT_LIST_ROUTE:"/dept-list",
    EMP_LIST_ROUTE:"/emp-list",
    EMP_LOGGEDIN_ROUTE:"/emp-details",
    MANAGER_LOGGEDIN_ROUTE:"/dept-mgmt",
    LOGIN_ROUTE:"/login",
    SIGNUP_ROUTE:"/signup",



}